//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public int StatusID { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
