//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwarePosition
    {
        public int SoftwarePositionID { get; set; }
        public int PositionID { get; set; }
        public int SoftwareID { get; set; }
        public int LicenseID { get; set; }
    
        public virtual LicensiaInfo LicensiaInfo { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Software Software { get; set; }
    }
}
