//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Software()
        {
            this.SoftwarePosition = new HashSet<SoftwarePosition>();
        }
    
        public int SoftwareID { get; set; }
        public string SoftwareName { get; set; }
        public Nullable<System.DateTime> LicenseExpirationDate { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public string WebUrl { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string UpdateDescription { get; set; }
        public Nullable<int> FileID { get; set; }
    
        public virtual Files Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwarePosition> SoftwarePosition { get; set; }
    }
}
